server:
  port: ${sms.service.orders.port}

eureka:
  instance:
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: ${sms.eureka.defaultZone}

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${sms.kafka.hostname}
      bindings:
        sms:
          destination: main stream
          contentType: application/json